version: "3.8"

services:
  dotnet-api:
    image: dotnet-api:latest
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "1"
          memory: "1G"
      restart_policy:
        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: overlay
